### ISSUE TITLE
How to start a new VSTS Docker Agent each build?

### ISSUE THREAD

**Issue by joaoasrosa** [Microsoft/vsts-agent-docker#131] opened 2018-08-09 14:45 UTC
Hi,
I can't find information on how to start a new VSTS Docker Agent each time a build is triggered. 

Perhaps is a chicken and egg problem, but the ideal scenario is:
1. Code commit
2. Start the container with capabilities
3. Run the build process inside of the container
4. Stop and dispose of the container after the build finish (successful or failure)

Any documentation around this scenario?

Thanks

**EDIT on 24/08/2028** - Similar to the feature *per-build container* offered by Atlassian.

**Comment by kbdavis07** [comment] 2018-08-19 20:13
I am thinking of the same thing, but so far could not find any documentation or examples doing this.

**Comment by gravufo** [comment] 2018-08-28 21:09
This isn't an actual solution, but it should help you start your own setup to do something like that: https://www.noelbundick.com/posts/serverless-vsts-build-agents-with-azure-container-instances/

It definitely isn't integrated in TFS/VSTS right now AFAIK. I would also like to do something like this in the future. If by then Microsoft implements the feature, I'll be very happy!

**Comment by joaoasrosa** [comment] 2018-08-28 21:15
Hi @gravufo,

Thanks for sharing your solution. I had something like that in mind. I would imagine the VSTS engine will work on the same way (at the moment the offer of Microsoft Hosted Agents does the spin up/teardown).

**Comment by joaoasrosa** [comment] 2018-08-28 21:58
Thanks for the heads up. Anyway, you gave a resource to do it.

**Comment by dakale** [comment] 2018-09-04 15:02
Mostly duplicate of https://github.com/Microsoft/vsts-agent-docker/issues/33

Summary: This has been asked for a lot and is something being worked on.

**Closed by dakale** 2018-09-04 15:02 UTC
