### ISSUE TITLE
Container stuck in "Restarting" When Docker Daemon is Restarted

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Microsoft/vsts-agent-docker#17] opened 2017-03-30 17:32 UTC
Using vsts-agent:ubuntu-16.04-docker-1.12.1-standard. 

When run via 

`docker run --restart=always <blah> -d microsoft/vsts-agent:ubuntu-16.04-docker-1.12.1-standard `.

and if the docker service is restarted, the vsts-agent-docker container does not recover from the "Restarting (xx minutes)" . This is causing perception issues that this is not reliable and is preventing adoption of this for our non .net dev. 

After doing some research, is this because of improper handling of SIGTERM? It seems that a fork of this 
vsts-agent-docker [here](https://hub.docker.com/r/ppanyukov/vsts-agent-d/) advertises:

> graceful restarts in case of crashes (e.g. with docker run -d --restart=always)

and 

> correct handling of SIGTERM

I am unable to try this as it is not a standard version that I require with the Java toolchain.

**Comment by stepro** [comment] 2017-03-30 18:10
Interesting that this doesn't work. We've been successfully running VSTS agents in DC/OS for a long time and DC/OS has an automatic restart policy that seems to work fine. There was very explicit work done around SIGTERM to ensure it gracefully cleans up when you send it a SIGTERM (or SIGINT). I'll take a look.

**Comment by AmitBhatnagar24** [comment] 2017-03-30 18:17
@stepro thanks. I appreciate it. 

perhaps some more relevant info:

`uname -a
Linux myServer.me.not.you 3.10.0-327.13.1.el7.x86_64 #1 SMP Mon Feb 29 13:22:02 EST 2016 x86_64 x86_64 x86_64 GNU/Linux`

`docker --version
Docker version 1.10.3, build 20f81dd`

**Comment by AmitBhatnagar24** [comment] 2017-03-30 18:40
@stepro Some details about the potential fixes from the forked repo I mentioned above:

https://github.com/ppanyukov/vso-agent-docker/issues/21

**Comment by stepro** [comment] 2017-03-30 19:23
Ok, this has nothing to do with SIGTERM handling. The issue is that start.sh has some incorrect handling for the case where you stop and restart the container. When you stop, it removes the agent from VSTS and as a result, loses its configuration. When you start it again, it identifies that the /vsts/agent directory already exists and assumes that the agent has been pre-configured (this scenario is used by the VSTS hosted Linux build agents). In case of a simple stop and restart, the agent has been downloaded but the configuration is missing.

I'll work on a fix and try to get it out in the next few days.

**Comment by stepro** [comment] 2017-03-31 23:40
The fix has been pushed and all the Docker Hub images are updated.

**Closed by stepro** 2017-03-31 23:40 UTC
